services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env



