# Generated by Django 5.1.3 on 2025-05-16 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_alter_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
