# Generated by Django 5.1.3 on 2025-05-30 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_remove_product_stock_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='date_received',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
